### ISSUE TITLE
Add APEX and Kermantech Mk3 IVA

### ISSUE THREAD

**Issue by harveyt** [FirstPersonKSP/reviva#8]
https://forum.kerbalspaceprogram.com/index.php?/topic/206744-112x-reviva-the-iva-revival-and-editorflight-switcher-now-with-airplane-plus-bdb-apollo-cm-075-29th-apr-2022/&do=findComment&comment=4139721

**Comment by JonnyOThan** [comment]
I may be adopting one or both of these mods, and if that happens I can add Reviva support directly to them.  Just something to keep in mind…it might be harder to undo a direct patch to Reviva in the future.
